2024-10-29 21:47:38,013 | WARNING | Неверный тип данных для объекта Runner
Traceback (most recent call last):
  File "E:\PyCharm Community Edition 2023.3.2\PycharmProjects\Urban University\Module12\tests_12_4.py", line 22, in test_run
    r = rtw.Runner(7)
        ^^^^^^^^^^^^^
  File "E:\PyCharm Community Edition 2023.3.2\PycharmProjects\Urban University\Module12\rt_with_exceptions.py", line 6, in __init__
    raise TypeError(f'Имя может быть только строкой, передано {type(name).__name__}')
TypeError: Имя может быть только строкой, передано int
2024-10-29 21:47:38,015 | WARNING | Неверная скорость для Runner
Traceback (most recent call last):
  File "E:\PyCharm Community Edition 2023.3.2\PycharmProjects\Urban University\Module12\tests_12_4.py", line 12, in test_walk
    r = rtw.Runner('Bob', -1)
        ^^^^^^^^^^^^^^^^^^^^^
  File "E:\PyCharm Community Edition 2023.3.2\PycharmProjects\Urban University\Module12\rt_with_exceptions.py", line 11, in __init__
    raise ValueError(f'Скорость не может быть отрицательной, сейчас {speed}')
ValueError: Скорость не может быть отрицательной, сейчас -1
